import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Input, Switch, Dropdown, Option, SpinButton, } from '@fluentui/react-components';
import { CollapsibleSection, FieldGroup } from '../CollapsibleSection';
import { BindingEditor } from './binding-editor/BindingEditor';
import { StyleEditor } from '../style-editor/StyleEditor';
import { LAYOUT_OPTIONS, FOOTER_ALIGNMENT_OPTIONS } from '../PropertyPanel.models';
export const CardEditor = ({ template, onUpdateCard, onUpdateRoot, classes, bindingPaths, className, }) => {
    const title = typeof template.card.title === 'string'
        ? template.card.title
        : (template.card.title?.value ?? '');
    const subtitle = typeof template.card.subtitle === 'string'
        ? template.card.subtitle
        : (template.card.subtitle?.value ?? '');
    return (_jsxs("div", { className: className, children: [_jsxs(CollapsibleSection, { title: "Template", classes: classes, children: [_jsx(FieldGroup, { label: "Name", className: classes.field, children: _jsx(Input, { size: "small", value: template.name, onChange: (_, d) => onUpdateRoot({ name: d.value }) }) }), _jsx(FieldGroup, { label: "Description", className: classes.field, children: _jsx(Input, { size: "small", value: template.description ?? '', onChange: (_, d) => onUpdateRoot({ description: d.value }) }) }), _jsx(FieldGroup, { label: "Version", className: classes.field, children: _jsx(Input, { size: "small", value: template.version, onChange: (_, d) => onUpdateRoot({ version: d.value }) }) })] }), _jsxs(CollapsibleSection, { title: "Card Content", classes: classes, children: [_jsx(FieldGroup, { label: "Title", className: classes.field, children: _jsx(Input, { size: "small", value: title, onChange: (_, d) => onUpdateCard({ title: d.value }) }) }), _jsx(FieldGroup, { label: "Title Binding", className: classes.field, children: _jsx(BindingEditor, { placeholder: "e.g. request.title", bindingPaths: bindingPaths, value: typeof template.card.title === 'object'
                                ? (template.card.title?.binding ?? '')
                                : '', onChange: (v) => onUpdateCard({
                                title: v ? { value: title, binding: v } : title,
                            }) }) }), _jsx(FieldGroup, { label: "Subtitle", className: classes.field, children: _jsx(Input, { size: "small", value: subtitle, onChange: (_, d) => onUpdateCard({ subtitle: d.value || undefined }) }) })] }), _jsxs(CollapsibleSection, { title: "Layout", classes: classes, children: [_jsx(FieldGroup, { label: "Direction", className: classes.field, children: _jsx(Dropdown, { size: "small", value: template.card.layout ?? 'stack', selectedOptions: [template.card.layout ?? 'stack'], onOptionSelect: (_, d) => onUpdateCard({ layout: d.optionValue }), children: LAYOUT_OPTIONS.map((l) => (_jsx(Option, { value: l, children: l }, l))) }) }), _jsxs("div", { className: classes.row, children: [_jsx(FieldGroup, { label: "Columns", className: classes.halfField, children: _jsx(SpinButton, { size: "small", value: template.card.columns ?? 1, min: 1, max: 12, onChange: (_, d) => onUpdateCard({ columns: d.value ?? undefined }) }) }), _jsx(FieldGroup, { label: "Gap", className: classes.halfField, children: _jsx(SpinButton, { size: "small", value: template.card.gap ?? 0, min: 0, max: 64, onChange: (_, d) => onUpdateCard({ gap: d.value ?? undefined }) }) })] }), _jsx(FieldGroup, { label: "Height", className: classes.field, children: _jsx(Input, { size: "small", placeholder: "e.g. 400px, 50vh", value: template.card.height != null ? String(template.card.height) : '', onChange: (_, d) => onUpdateCard({ height: d.value || undefined }) }) }), _jsxs("div", { className: classes.row, children: [_jsx(Switch, { label: "Collapsible", checked: template.card.isCollapsible ?? false, onChange: (_, d) => onUpdateCard({ isCollapsible: d.checked }) }), _jsx(Switch, { label: "Default Expanded", checked: template.card.defaultExpanded ?? true, onChange: (_, d) => onUpdateCard({ defaultExpanded: d.checked }) })] })] }), _jsx(CollapsibleSection, { title: "Footer", classes: classes, children: _jsx(FieldGroup, { label: "Alignment", className: classes.field, children: _jsx(Dropdown, { size: "small", value: template.card.footerAlignment ?? 'end', selectedOptions: [template.card.footerAlignment ?? 'end'], onOptionSelect: (_, d) => onUpdateCard({
                            footerAlignment: d.optionValue,
                        }), children: FOOTER_ALIGNMENT_OPTIONS.map((a) => (_jsx(Option, { value: a, children: a }, a))) }) }) }), _jsx(StyleEditor, { style: template.card.style, onChange: (s) => onUpdateCard({ style: s }), classes: classes })] }));
};
